CATEGORIES = [
    {"name": "Hardware", "description": "Physical component issues (fan, thermal, keyboard, storage)"},
    {"name": "Network", "description": "WiFi and Bluetooth connectivity issues"},
    {"name": "Display", "description": "Screen and video output issues"},
    {"name": "Battery", "description": "Power and charging issues"},
    {"name": "Operating System", "description": "Boot and system-level issues"},
    {"name": "Performance", "description": "Speed and responsiveness issues"},
]

# code must match the ML dataset labels exactly
PROBLEMS = [
    {
        "code": "overheating",
        "category": "Hardware",
        "name": "Overheating",
        "description": "The laptop runs hotter than normal and may shut down automatically to protect its components.",
        "severity": "HIGH",
        "time": (60, 120),
        "causes": ["Dust accumulation in the cooling system", "Degraded thermal paste", "Cooling fan malfunction", "Blocked air vents"],
        "steps": [
            ("Check CPU temperature", "Use a monitoring tool (e.g. HWMonitor) to check whether CPU temperature exceeds 85-90°C under load.", None, False),
            ("Check the cooling fan", "Listen for unusual noise and confirm the fan spins up under load.", None, False),
            ("Inspect the air vents", "Check the vents for dust or blockage and clean them with compressed air if needed.", None, False),
            ("Inspect the heatsink", "Open the back panel (if you're comfortable doing so) and check for dust buildup on the heatsink.", "Opening the laptop may void your warranty — skip this if unsure.", True),
            ("Check thermal paste condition", "If the laptop is more than 2 years old, dried thermal paste may need reapplying.", "This step is best done by a technician.", True),
            ("Retest after cleaning", "Run the laptop under normal load again and monitor whether temperatures stay stable.", None, True),
        ],
        "questions": [
            ("q_hot_before_shutdown", "Does the laptop become very hot before shutting down?"),
            ("q_fan_loud", "Does the cooling fan become very loud or spin at full speed?"),
        ],
    },
    {
        "code": "wifi_problem",
        "category": "Network",
        "name": "WiFi Connectivity Problem",
        "description": "The laptop cannot detect, connect to, or maintain a stable WiFi connection.",
        "severity": "MEDIUM",
        "time": (15, 45),
        "causes": ["Outdated or corrupted WiFi driver", "WiFi adapter disabled", "Router/network issue", "Airplane mode enabled"],
        "steps": [
            ("Check WiFi is enabled", "Make sure WiFi is turned on and airplane mode is off.", None, False),
            ("Restart the router", "Turn the router off for 10 seconds, then turn it back on.", None, False),
            ("Check Device Manager", "Open Device Manager and confirm the WiFi adapter is listed without a warning icon.", None, False),
            ("Update or reinstall the WiFi driver", "Download the latest driver from the manufacturer's site and reinstall it.", None, True),
            ("Run the network troubleshooter", "Use the built-in Windows network troubleshooter to detect common issues.", None, True),
        ],
        "questions": [
            ("q_wifi_visible", "Can you see your WiFi network in the list of available networks?"),
            ("q_other_devices_ok", "Can other devices connect to the same WiFi network normally?"),
        ],
    },
    {
        "code": "bluetooth_problem",
        "category": "Network",
        "name": "Bluetooth Connectivity Problem",
        "description": "Bluetooth cannot be enabled, or fails to pair/stay connected with devices.",
        "severity": "LOW",
        "time": (10, 30),
        "causes": ["Bluetooth driver issue", "Bluetooth disabled in BIOS", "Device pairing cache corrupted"],
        "steps": [
            ("Check Bluetooth is enabled", "Open Settings and confirm the Bluetooth toggle is on.", None, False),
            ("Restart Bluetooth service", "Toggle Bluetooth off and on, or restart the laptop.", None, False),
            ("Remove and re-pair the device", "Forget the paired device, then pair it again from scratch.", None, False),
            ("Update the Bluetooth driver", "Reinstall the Bluetooth driver from the manufacturer's website.", None, True),
        ],
        "questions": [
            ("q_bt_visible_settings", "Do you see a Bluetooth option in your settings at all?"),
            ("q_bt_other_devices", "Have you tried pairing with more than one device?"),
        ],
    },
    {
        "code": "black_screen",
        "category": "Display",
        "name": "Black Screen",
        "description": "The laptop powers on (fan spins, lights on) but the screen shows nothing.",
        "severity": "HIGH",
        "time": (30, 90),
        "causes": ["Graphics driver crash", "Loose display cable", "Failed GPU", "Corrupted OS boot"],
        "steps": [
            ("Force restart", "Hold the power button for 10 seconds, then turn the laptop back on.", None, False),
            ("Check external display", "Connect an external monitor to see if it also shows nothing (helps isolate the screen vs GPU).", None, False),
            ("Try Safe Mode", "Attempt to boot into Safe Mode to rule out a driver issue.", None, True),
            ("Inspect display cable/hinge", "For laptops with a detachable or flexible hinge, check if the display cable is loose.", "Requires opening the laptop chassis — technician recommended.", True),
        ],
        "questions": [
            ("q_screen_totally_black", "Is the screen completely black with no backlight at all?"),
            ("q_external_monitor_works", "If you connect an external monitor, does it show a picture?"),
        ],
    },
    {
        "code": "display_flickering",
        "category": "Display",
        "name": "Display Flickering",
        "description": "The screen flickers, shows unstable colors, or has flickering lines.",
        "severity": "MEDIUM",
        "time": (20, 60),
        "causes": ["Outdated graphics driver", "Loose display cable", "Incompatible refresh rate setting", "Failing display panel"],
        "steps": [
            ("Update the graphics driver", "Update or roll back your GPU driver to the latest stable version.", None, False),
            ("Check refresh rate settings", "Confirm the display refresh rate matches what your screen supports.", None, False),
            ("Test on battery vs charger", "Check whether flickering happens only when on battery or only when charging.", None, False),
            ("Inspect the display cable", "If flickering changes when you gently move the screen, the cable may be loose.", "Requires opening the laptop chassis — technician recommended.", True),
        ],
        "questions": [
            ("q_flicker_charger_only", "Does the flickering happen only when the laptop is unplugged or only when charging?"),
            ("q_flicker_worse_moving_screen", "Does flickering get worse when you move or adjust the screen angle?"),
        ],
    },
    {
        "code": "slow_performance",
        "category": "Performance",
        "name": "Slow Performance",
        "description": "The laptop is noticeably slower than usual, lags, or freezes during normal use.",
        "severity": "LOW",
        "time": (20, 60),
        "causes": ["Too many startup programs", "Storage almost full", "Malware", "Insufficient RAM for current workload"],
        "steps": [
            ("Check Task Manager", "Look for processes consuming unusually high CPU, memory, or disk usage.", None, False),
            ("Disable unnecessary startup apps", "Open Task Manager > Startup tab and disable apps you don't need at boot.", None, False),
            ("Check free storage space", "Confirm you have at least 15-20% free disk space.", None, False),
            ("Run a malware scan", "Use Windows Defender or another trusted tool to scan for malware.", None, True),
            ("Consider a RAM/SSD upgrade", "If the laptop is old and specs are low for your workload, a hardware upgrade may help.", None, True),
        ],
        "questions": [
            ("q_slow_specific_app", "Does the slowness happen with one specific app, or with everything?"),
            ("q_storage_almost_full", "Is your storage (C: drive) almost full?"),
        ],
    },
    {
        "code": "boot_problem",
        "category": "Operating System",
        "name": "Boot Failure",
        "description": "The laptop fails to start Windows, gets stuck on a loading screen, or restarts in a loop.",
        "severity": "HIGH",
        "time": (30, 120),
        "causes": ["Corrupted system files", "Failing storage drive", "Recent faulty update", "Loose internal storage connection"],
        "steps": [
            ("Force restart once", "Hold the power button for 10 seconds and try starting again.", None, False),
            ("Boot into Safe Mode", "Try Safe Mode to see if Windows can start with minimal drivers.", None, False),
            ("Run Startup Repair", "Use the Windows recovery environment's Startup Repair tool.", None, True),
            ("Check storage drive health", "Use a bootable diagnostic tool to check if the SSD/HDD is failing.", "If the drive is failing, back up data immediately before further troubleshooting.", True),
        ],
        "questions": [
            ("q_boot_bsod", "Do you see a blue screen with an error message?"),
            ("q_boot_after_update", "Did this start right after a Windows update or power outage?"),
        ],
    },
    {
        "code": "battery_not_charging",
        "category": "Battery",
        "name": "Battery Not Charging",
        "description": "The battery percentage doesn't increase even though the charger is connected.",
        "severity": "MEDIUM",
        "time": (15, 45),
        "causes": ["Faulty charger or cable", "Worn-out battery", "Charging port issue", "Battery driver glitch"],
        "steps": [
            ("Check the charger and cable", "Try a different charger/cable if available, and check for visible damage.", None, False),
            ("Check the charging port", "Inspect the port for dust, debris, or a loose connection.", None, False),
            ("Uninstall the battery driver", "In Device Manager, uninstall the battery driver and restart to let Windows reinstall it.", None, True),
            ("Check battery health report", "Run 'powercfg /batteryreport' in Command Prompt to check battery wear level.", None, True),
        ],
        "questions": [
            ("q_battery_light_on", "Does the charging light on the laptop turn on when plugged in?"),
            ("q_battery_percent_frozen", "Does the battery percentage stay exactly the same, or does it slowly drop even while plugged in?"),
        ],
    },
    {
        "code": "storage_problem",
        "category": "Hardware",
        "name": "Storage Problem",
        "description": "The drive is failing, corrupted, running out of space, or not being detected.",
        "severity": "HIGH",
        "time": (30, 90),
        "causes": ["Failing HDD/SSD", "File system corruption", "Storage nearly full", "Loose storage connection"],
        "steps": [
            ("Check free space", "Open File Explorer and confirm how much free space remains on the main drive.", None, False),
            ("Run CHKDSK", "Run 'chkdsk C: /f' from an elevated Command Prompt to check for file system errors.", None, False),
            ("Check drive health (SMART)", "Use a tool like CrystalDiskInfo to check the drive's SMART health status.", "If SMART status is 'Bad', back up your data immediately.", True),
            ("Back up important data", "If the drive shows any warning signs, back up your files right away before continuing.", None, True),
        ],
        "questions": [
            ("q_storage_clicking_noise", "Does the laptop make an unusual clicking or grinding noise?"),
            ("q_storage_files_corrupt", "Are files frequently becoming corrupted or failing to open?"),
        ],
    },
    {
        "code": "keyboard_problem",
        "category": "Hardware",
        "name": "Keyboard Problem",
        "description": "One or more keys don't respond, register wrong characters, or the keyboard doesn't work at all.",
        "severity": "LOW",
        "time": (15, 45),
        "causes": ["Debris stuck under the keys", "Liquid spill damage", "Keyboard driver issue", "Loose keyboard ribbon cable"],
        "steps": [
            ("Restart the laptop", "A simple restart can resolve temporary keyboard driver glitches.", None, False),
            ("Clean the keyboard", "Turn off the laptop and gently clean around and under the keys with compressed air.", None, False),
            ("Test with an external keyboard", "Plug in a USB keyboard to check whether the issue is with the built-in keyboard specifically.", None, False),
            ("Update the keyboard driver", "In Device Manager, update or reinstall the keyboard driver.", None, True),
            ("Inspect for liquid damage", "If liquid was ever spilled, professional cleaning/repair may be required.", "Do not attempt to open the laptop yourself if liquid damage is suspected.", True),
        ],
        "questions": [
            ("q_keyboard_liquid_spill", "Has any liquid been spilled on the laptop recently?"),
            ("q_keyboard_external_works", "Does an external USB keyboard work normally when connected?"),
        ],
    },
]

QUESTIONS_BY_CODE = {p["code"]: p["questions"] for p in PROBLEMS}

